### PR TITLE
feat: Add Flax Layers

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Adds Flax Module's for einops operations. More details can be found in #153 

einops supports JAX arrays, so I'm unsure if I should add tests or not ?

CC: @arogozhnikov

### CODE REVIEW

**Comment by arogozhnikov** [comment]
>  I should add tests or not 

Yes, tests are needed, because we need to ensure that following things are working:

1. serialization/deserialization of weights
2. serialization/deserialization/pickling/deepcopy-ing of models
3. layers normally interact with other layers 

For other frameworks, I just have some lenet-style model with layers, and check that 1 and 2 work for the whole model

**Comment by arogozhnikov** [comment]
@SauravMaheshkar here is an example for torch:
https://github.com/arogozhnikov/einops/blob/master/tests/test_layers.py#L200-L231

Goal of adding tests is to make sure that layers can be serialized / deserialized using native flax serialization mechanisms

**Comment by SauravMaheshkar** [comment]
Request for Clarification:

```python
has_flax = any(backend.framework_name == 'jax' for backend in collect_test_backends(symbolic=False, layers=True))
```

would be the correct way ?

**Comment by arogozhnikov** [comment]
hm. Yes, that's tricky, flax doesn't have own backend.

```
try:
    import flax
    has_flax = True
except:
    has_flax = False
```

**Comment by arogozhnikov** [comment]
Hi @SauravMaheshkar I think something was changed in the flax, because the code does not work. 

I have another implementation #214 that *propbably* accounts for all strangeness of flax, so closing this. Testing is very welcome!

**Pull request closed without merging**
