### PR TITLE
Wrap torch symbolic shape as HashableTuple to mitigate unhashable torch.SymInt

### PR DESCRIPTION
**Pull request by yanboliang**
This is a potential fix for https://github.com/pytorch/pytorch/issues/93905 and https://github.com/pytorch/pytorch/issues/105686.

### CODE REVIEW

**Comment by yanboliang** [comment]
cc @arogozhnikov

**Comment by arogozhnikov** [comment]
@yanboliang thanks for PR.
I've been thinking also about the case of non-hashable axis lengths.

Check this branch against torch tests, I've tried to address that without losing efficiency for eager mode:
https://github.com/arogozhnikov/einops/compare/torch-dynamic-compile

If that works ok, I'll merge that.

**Comment by arogozhnikov** [comment]
ping @yanboliang

**Comment by yanboliang** [comment]
Yes, your PR can fix https://github.com/pytorch/pytorch/issues/105686. Thanks for the fix!

**Pull request closed without merging**
