### PR TITLE
tensorflow layers

### PR DESCRIPTION
**Pull request by adam-r-kowalski**
I love your project, it has really changed the way I write my code. I wanted to be able to use it in the TensorFlow version of Keras as well. I only had to change one thing since the dimensions are represented differently.

### CODE REVIEW

**Comment by adam-r-kowalski** [comment]
I also added a modified version of the README which translates the PyTorch code so that it uses TensorFlow as appropriate.

**Comment by arogozhnikov** [comment]
Hi Adam, 

> I love your project, it has really changed the way I write my code.

thanks for sharing your experience! Chainging the coding is a goal of this project.

I'm looking at proposed changes - how is proposed code different from keras layers. Can't we use those instead?

**Comment by adam-r-kowalski** [comment]
I tried, but I was getting an exception thrown unfortunately. The dimensions in TensorFlow need to be manipulated slightly differently. All I needed to do was call `.value` on them when iterating over the dimensions, besides that the code is unchanged.

**Comment by arogozhnikov** [comment]
Ok, I see now the problem.

I need some time to dig inside tf.layers to understand reasons.

**Comment by adam-r-kowalski** [comment]
That doesn't work for me. I think Keras expects you to implement compute_output_shape.

**Comment by arogozhnikov** [comment]
@adam-r-kowalski 

I've created an issue for that, could you please write a minimal example what is not working in issue #27?

**Pull request merged**
